/* eslint-disable import/no-anonymous-default-export */
export default [
  { code: 11, name: "São Paulo" },
  { code: 12, name: "São Paulo" },
  { code: 13, name: "São Paulo" },
  { code: 14, name: "São Paulo" },
  { code: 15, name: "São Paulo" },
  { code: 16, name: "São Paulo" },
  { code: 17, name: "São Paulo" },
  { code: 18, name: "São Paulo" },
  { code: 19, name: "São Paulo" },
  { code: 21, name: "Rio de Janeiro" },
  { code: 22, name: "Rio de Janeiro" },
  { code: 24, name: "Rio de Janeiro" },
  { code: 27, name: "Espírito Santo" },
  { code: 28, name: "Espírito Santo" },
  { code: 31, name: "Minas Gerais" },
  { code: 32, name: "Minas Gerais" },
  { code: 33, name: "Minas Gerais" },
  { code: 34, name: "Minas Gerais" },
  { code: 35, name: "Minas Gerais" },
  { code: 37, name: "Minas Gerais" },
  { code: 38, name: "Minas Gerais" },
  { code: 41, name: "Paraná" },
  { code: 42, name: "Paraná" },
  { code: 43, name: "Paraná" },
  { code: 44, name: "Paraná" },
  { code: 45, name: "Paraná" },
  { code: 46, name: "Paraná" },
  { code: 47, name: "Santa Catarina" },
  { code: 48, name: "Santa Catarina" },
  { code: 49, name: "Santa Catarina" },
  { code: 51, name: "Rio Grande do Sul" },
  { code: 53, name: "Rio Grande do Sul" },
  { code: 54, name: "Rio Grande do Sul" },
  { code: 55, name: "Rio Grande do Sul" },
  { code: 61, name: "Distrito Federal" },
  { code: 62, name: "Goiás" },
  { code: 64, name: "Goiás" },
  { code: 63, name: "Tocantins" },
  { code: 65, name: "Mato Grosso" },
  { code: 66, name: "Mato Grosso" },
  { code: 67, name: "Mato Grosso do Sul" },
  { code: 68, name: "Acre" },
  { code: 69, name: "Rondônia" },
  { code: 71, name: "Bahia" },
  { code: 73, name: "Bahia" },
  { code: 74, name: "Bahia" },
  { code: 75, name: "Bahia" },
  { code: 77, name: "Bahia" },
  { code: 79, name: "Sergipe" },
  { code: 81, name: "Pernambuco" },
  { code: 87, name: "Pernambuco" },
  { code: 82, name: "Alagoas" },
  { code: 83, name: "Paraíba" },
  { code: 84, name: "Rio Grande do Norte" },
  { code: 85, name: "Ceará" },
  { code: 88, name: "Ceará" },
  { code: 86, name: "Piauí" },
  { code: 89, name: "Piauí" },
  { code: 91, name: "Pará" },
  { code: 93, name: "Pará" },
  { code: 94, name: "Pará" },
  { code: 92, name: "Amazonas" },
  { code: 97, name: "Amazonas" },
  { code: 95, name: "Roraima" },
  { code: 96, name: "Amapá" },
  { code: 98, name: "Maranhão" },
  { code: 99, name: "Maranhão" },
];
